# Generated by Django 6.0.1 on 2026-01-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
