# Generated by Django 5.2.6 on 2025-12-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff/Mentor'), ('admin', 'Admin/Librarian')], default='admin', max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff/Mentor'), ('admin', 'Admin/Librarian')], default='staff', max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff/Mentor'), ('admin', 'Admin/Librarian')], default='student', max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
