# Generated by Django 5.2.6 on 2025-12-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_admin_is_approved_staff_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_approved',
        ),
    ]
