# Generated by Django 5.2.6 on 2025-12-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_admin_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
