# Generated by Django 5.2.6 on 2025-12-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(choices=[('Major Project', 'Major Project'), ('Minor Project', 'Minor Project')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('keywords', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('submission_date', models.DateField()),
                ('team_leader', models.CharField(max_length=100)),
                ('team_leader_reg', models.CharField(max_length=50)),
                ('member1', models.CharField(max_length=100)),
                ('member1_reg', models.CharField(max_length=50)),
                ('member2', models.CharField(max_length=100)),
                ('member2_reg', models.CharField(max_length=50)),
                ('member3', models.CharField(max_length=100)),
                ('member3_reg', models.CharField(max_length=50)),
                ('member4', models.CharField(blank=True, max_length=100, null=True)),
                ('member4_reg', models.CharField(blank=True, max_length=50, null=True)),
                ('member5', models.CharField(blank=True, max_length=100, null=True)),
                ('member5_reg', models.CharField(blank=True, max_length=50, null=True)),
                ('member6', models.CharField(blank=True, max_length=100, null=True)),
                ('member6_reg', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028')], max_length=20)),
                ('file', models.FileField(upload_to='projects/')),
            ],
        ),
    ]
