# Generated by Django 5.2.6 on 2025-12-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_deatils', '0002_project_upload_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_upload',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
