# Generated by Django 5.2.6 on 2025-12-08 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_deatils', '0003_project_upload_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_upload',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('accession_number', models.IntegerField()),
                ('project_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_deatils.project_upload')),
            ],
        ),
    ]
