# Generated by Django 5.2.6 on 2025-12-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_deatils', '0005_downloadrecord_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadRecord',
        ),
    ]
